// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUfo1fjSWpwyU5XRmDyhqhVfY2mm1Dokc',
    appId: '1:425703804902:web:8a3b9d722727022d9d9027',
    messagingSenderId: '425703804902',
    projectId: 'findit-421d5',
    authDomain: 'findit-421d5.firebaseapp.com',
    storageBucket: 'findit-421d5.firebasestorage.app',
    measurementId: 'G-N7NDEKND0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJ93ZsY915-517yQQh2-LIgULfLrCKcs',
    appId: '1:425703804902:android:de94610250aba7799d9027',
    messagingSenderId: '425703804902',
    projectId: 'findit-421d5',
    storageBucket: 'findit-421d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjaDGJ8BR4BYjj8fE_SgJ6kVEUb7OFK-w',
    appId: '1:425703804902:ios:17e52d1596c622fb9d9027',
    messagingSenderId: '425703804902',
    projectId: 'findit-421d5',
    storageBucket: 'findit-421d5.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjaDGJ8BR4BYjj8fE_SgJ6kVEUb7OFK-w',
    appId: '1:425703804902:ios:17e52d1596c622fb9d9027',
    messagingSenderId: '425703804902',
    projectId: 'findit-421d5',
    storageBucket: 'findit-421d5.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUfo1fjSWpwyU5XRmDyhqhVfY2mm1Dokc',
    appId: '1:425703804902:web:e61e0fd7fc96efd59d9027',
    messagingSenderId: '425703804902',
    projectId: 'findit-421d5',
    authDomain: 'findit-421d5.firebaseapp.com',
    storageBucket: 'findit-421d5.firebasestorage.app',
    measurementId: 'G-3Q9M0DSS80',
  );
}
